/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_icui4cu_ndk_demo2_libHelloJni */

#ifndef _Included_com_example_icui4cu_ndk_demo2_libHelloJni
#define _Included_com_example_icui4cu_ndk_demo2_libHelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_icui4cu_ndk_demo2_libHelloJni
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_icui4cu_ndk_1demo2_libHelloJni_getCLanguageString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
